server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/student-service/**
              filters:
                - StripPrefix=1
            - id: address-service
              uri: lb://address-service
              predicates:
                - Path=/address-service/**
              filters:
                - StripPrefix=1
            - id: eureka-server
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/main
              filters:
                - StripPrefix=1
                - SetPath=/
              

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3 # or w3c (default for OTel is w3c, for Brave is b3)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
